version: '3'
services:
  kibana:
    image: kibana:7.13.2
    container_name: kibana-single
    restart: always
    ports:
        - 5601:5601
    volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
        SERVER_NAME: "http://kabana.lupingguo.woa.com"
        ELASTICSEARCH_HOSTS: "http://es-single:9200"
    networks:
        - elastic
    depends_on:
        - es-single
  es-single: 
    image: elasticsearch:7.13.2
    container_name: es-single
    restart: always
    ports:
        - 9200:9200
        - 9300:9300
    volumes:
        - /data/docker_volumes/single_node/:/usr/share/elasticsearch/data/
    networks:
        - elastic
    environment:
        - node.name=es-single
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
    elastic:
