version: '3'
services:
  kibana:
    image: kibana:7.13.2
    container_name: kibana01
    restart: always
    ports:
        - 5601:5601
    volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
        SERVER_NAME: "kabana.lupingguo.woa.com"
        ELASTICSEARCH_HOSTS: "http://es01:9200"
    networks:
        - elastic-cluster
    depends_on:
        - es01
  es01:
    image: elasticsearch:7.13.2
    container_name: es01
    restart: always
    ports:
        - 9200:9200
        - 9300:9300
    volumes:
        #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - /data/docker_volumes/cluster_nodes/data01:/usr/share/elasticsearch/data
    networks:
        - elastic-cluster
    environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es02,es03
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es02:
    image: elasticsearch:7.13.2
    container_name: es02
    restart: always
    volumes:
        #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - /data/docker_volumes/cluster_nodes/data02:/usr/share/elasticsearch/data
    networks:
        - elastic-cluster
    environment:
        - node.name=es02
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es01,es03
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es03:
    image: elasticsearch:7.13.2
    container_name: es03
    restart: always
    volumes:
        #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - /data/docker_volumes/cluster_nodes/data03:/usr/share/elasticsearch/data
    networks:
        - elastic-cluster
    environment:
        - node.name=es03
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es01,es02
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
    elastic-cluster:
